site_name: Team Wiki
repo_name: https://github.com/WUST-mengqinyu/Team-Wiki
site_url: https://wiki.verly-badcw.top

theme: yeti

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics: ['UA-139418303-1', 'wiki.verly-badcw.top']

markdown_extensions:
    - extra
    - tables
    - toc
    - fenced_code
    - smarty
    - mdx_math:
        enable_dollar_delimiter: True
    - footnotes

copyright: Copyright &copy;  <a href="https://wiki.verly-badcw.top" target="_blank">wiki.verly-badcw.top</a>