site_name: Team Wiki
repo_name: https://github.com/WUST-mengqinyu/Team-Wiki
site_url: https://wiki.verly-badcw.top
nav:
  - 主页:
    - 2019赛季: index.md
    - Wannafly Winter Camp: Wannafly Winter Camp 2020.md
  - 个人页面:
    - Verly: Personal Page/Verly/index.md
    - badcw: Personal Page/badcw/index.md
  - 专题:
    - SegmentTree2: Topic Training/SegmentTree2.md

theme: # yeti
    name: null
    custom_dir: 'mkdocs-material/material'
    palette:
        primary: white

    language: 'en'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: "cloud"
    feature:
        tabs: true

extra_css:
  - 'stylesheets/extra.css'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

google_analytics: 
    - 'UA-139418303-1'
    - 'wiki.verly-badcw.top'

markdown_extensions:
    - extra
    - tables
    - toc:
        permalink: Link
    - fenced_code
    - smarty
    - mdx_math:
        enable_dollar_delimiter: True
    - footnotes
    - admonition
    - codehilite:
        guess_lang: false
        linenums: true
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.progressbar

copyright: Copyright &copy;  <a href="https://wiki.verly-badcw.top" target="_blank">wiki.verly-badcw.top</a>
